// src/components/Navbar.vue
<template>
    <nav class="navbar">
        <img src="../assets/img/logo.png" alt="" class="logo">
        <div class="nav-center">
            <a href="#" class="nav-item">News</a>
            <a href="#" class="nav-item">About</a>
            <a href="#" class="nav-item">Community</a>
        </div>
        <div class="nav-options">
            <a href="#" class="icon"><img src="../assets/img/search.png" alt="search"></a>
            <a href="#" class="icon"><img src="../assets/img/user.png" alt="user"></a>
        </div>
    </nav>
</template>
<style scoped>  
    .navbar {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin-left: 5%;
        margin-right: 5%;
        align-items: center;
    }

    .navbar .nav-center {
        display: flex;
        width: max-content;
        gap: 20px;
    }

    .navbar .nav-item {
        text-decoration: none;
        color: #121212;
    }
    .navbar .nav-options{
        display: flex;
        gap: 20px;
    }
</style>

// src/components/NavBar.tsx
import NavData from "../helpers/NavData";
function NavBar() {
  const navItems = NavData();
  return (
    <nav className="navbar">
      <img src="/img/logo.png" alt="" className="logo" />
      <div className="nav-center">
        {navItems.map((item, index) => (
          <a href={item.url} key={index} className="nav-item">
            {item.title}
          </a>
        ))}
      </div>
      <div className="nav-options">
        <a href="#" className="icon">
          <img src="/img/search.png" alt="search" />
        </a>
        <a href="#" className="icon">
          <img src="/img/user.png" alt="user" />
        </a>
      </div>
    </nav>
  );
}
export default NavBar;
